# Generated by Django 5.0.6 on 2024-05-16 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="content",
            field=models.TextField(
                blank=True, help_text="Введите текст", null=True, verbose_name="Текст"
            ),
        ),
        migrations.AddField(
            model_name="blog",
            name="title",
            field=models.CharField(
                default=None,
                help_text="Введите заголовок",
                max_length=60,
                verbose_name="Заголовок",
            ),
        ),
    ]
