# Generated by Django 5.0.6 on 2024-06-01 19:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_blog_created_at_blog_is_published_blog_photo_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="created_at",
            field=models.DateField(
                default=datetime.date(2024, 6, 1),
                help_text="Укажите дату создания",
                verbose_name="Дата создания",
            ),
        ),
    ]
