# Generated by Django 5.0.6 on 2024-06-02 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_alter_blog_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="created_at",
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
