# Generated by Django 4.2 on 2024-06-14 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0006_alter_blog_created_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blog",
            options={
                "permissions": [
                    ("change_content_blog", "Change content blog"),
                    ("change_title_blog", "Change title blog"),
                    ("unpublish_a_blog", "Unpublish a blog"),
                ],
                "verbose_name": "Блог",
                "verbose_name_plural": "Блоги",
            },
        ),
    ]
