# Generated by Django 5.0.6 on 2024-06-01 18:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_contact"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="created_at",
            field=models.DateField(
                default=datetime.date(2024, 6, 1),
                help_text="Укажите дату создания",
                verbose_name="Дата создания",
            ),
        ),
    ]
