# Generated by Django 4.2 on 2024-06-13 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_product_owner"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["category", "name", "price", "created_at", "updated_at"],
                "permissions": [
                    ("unpublish_a_product", "Unpublish a product"),
                    ("change_description,", "Change description"),
                    ("change_category", "Change category"),
                ],
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
            },
        ),
        migrations.AddField(
            model_name="product",
            name="is_published",
            field=models.BooleanField(
                blank=True,
                default=True,
                help_text="Укажите статус публикации",
                null=True,
                verbose_name="Публикация",
            ),
        ),
    ]
