# Generated by Django 4.2 on 2024-06-14 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0009_alter_product_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["category", "name", "price", "created_at", "updated_at"],
                "permissions": [
                    ("unpublish_a_product", "Unpublish a product"),
                    ("change_description_product,", "Change description product"),
                    ("change_category_product", "Change category product"),
                ],
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
            },
        ),
    ]
